"""Persistence port implemented by infrastructure adapters."""

from typing import Protocol

from src.classifier.models import ClassificationResult
from src.domain.models import FlowState, InboundMessage, Priority


class ConversationRepository(Protocol):
    async def initialize(self) -> None: ...

    async def record_inbound(self, message: InboundMessage) -> bool: ...

    async def has_consent(self, wa_id: str) -> bool: ...

    async def record_consent(self, wa_id: str, accepted: bool) -> None: ...

    async def set_state(self, wa_id: str, state: FlowState) -> None: ...

    async def get_open_appointment(self, wa_id: str) -> dict[str, str] | None: ...

    async def save_appointment(
        self, wa_id: str, slots: dict[str, str], status: str = "collecting"
    ) -> None: ...

    async def record_classification(
        self, message_id: str, result: ClassificationResult
    ) -> None: ...

    async def record_escalation(
        self, wa_id: str, reason: str, priority: Priority, result: ClassificationResult
    ) -> None: ...

    async def queue_outbound(self, wa_id: str, text: str) -> str: ...

    async def mark_outbound_sent(self, local_id: str, meta_id: str | None = None) -> None: ...

    async def mark_outbound_failed(self, local_id: str, error: str) -> None: ...

    async def update_delivery_status(self, meta_id: str, status: str) -> None: ...

    async def list_messages(self, wa_id: str) -> list[dict[str, object]]: ...

    async def list_escalations(self) -> list[dict[str, object]]: ...
